name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: Clean solution
        run: dotnet clean

      - name: Restore solution
        run: dotnet restore

      - name: Run the Cake script
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.2.0
          verbosity: Diagnostic

      - uses: actions/upload-artifact@v4
        with:
          name: Mitochondria
          path: build/bin/

      - uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: build/packages/

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: |
            build/archives/*
            build/packages/*
